//! The message envelope.
//!
//! Shape is taken from ACP: an ordered list of typed parts rather than a bare
//! string, so a message can carry a rendered notice alongside its text without
//! either being parsed back out of prose. Provenance (`cause`, `hop`, `run`)
//! is Guac's own addition; none of the surveyed protocols carry enough
//! causality to reconstruct who set off a cascade, which is the first thing you
//! want when agents start talking to each other.

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use super::ids::{AgentId, MessageId, RunId};

/// Who is at one end of an envelope.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum Participant {
    /// The person at the keyboard.
    Human,
    Agent {
        id: AgentId,
    },
    /// Guac itself, for guard notices and lifecycle records.
    System,
}

impl Participant {
    pub fn agent_id(&self) -> Option<AgentId> {
        match self {
            Participant::Agent { id } => Some(*id),
            _ => None,
        }
    }

    pub fn is_agent(&self) -> bool {
        matches!(self, Participant::Agent { .. })
    }
}

/// Why the receiving model should or should not believe this content.
///
/// This is the survey's threat model made mechanical. MCP calls it tool
/// poisoning, A2A calls it task injection; both describe the same failure,
/// where text that arrived over the wire is treated as an instruction from the
/// principal. Guac tags provenance at the envelope and re-states it in the
/// prompt, so a peer's text arrives as a quoted claim rather than as orders.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Trust {
    /// Typed by the operator. The only content treated as authoritative.
    Operator,
    /// Produced by a model. Data, not instructions.
    Peer,
    /// Generated by Guac (guard notices, lifecycle records).
    System,
}

impl Trust {
    pub fn as_str(self) -> &'static str {
        match self {
            Trust::Operator => "operator",
            Trust::Peer => "peer",
            Trust::System => "system",
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "operator" => Some(Trust::Operator),
            "peer" => Some(Trust::Peer),
            "system" => Some(Trust::System),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum NoticeKind {
    /// The loop guard refused something.
    GuardStop,
    /// An upstream inference call failed.
    UpstreamError,
    /// Lifecycle transition worth showing in the transcript.
    Lifecycle,
}

/// One typed segment of a message.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "camelCase", rename_all_fields = "camelCase")]
pub enum Part {
    Text {
        text: String,
    },
    /// A structured artifact. `name` is the semantic tag ACP uses to let a
    /// downstream reader know what it is looking at without sniffing.
    Json {
        name: String,
        value: serde_json::Value,
    },
    /// Guac speaking, rendered as a system chip rather than as dialogue.
    Notice {
        kind: NoticeKind,
        text: String,
    },
    /// A record that this agent called a tool. Kept as its own part so the UI
    /// can show the reasoning trail without it polluting the transcript text.
    ToolCall {
        name: String,
        arguments: serde_json::Value,
        outcome: ToolOutcome,
    },
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "status", rename_all = "camelCase", rename_all_fields = "camelCase")]
pub enum ToolOutcome {
    Ok {
        summary: String,
    },
    /// Some recipients took it and some did not.
    ///
    /// A fan-out has no single verdict. Reporting the whole call "ok" because
    /// one message got through drew every recipient as delivered, including the
    /// ones that were refused, so the operator read "Sent to Researcher" about a
    /// message Researcher never received.
    Partial {
        summary: String,
        refused: Vec<RefusedRecipient>,
    },
    Refused {
        reason: String,
    },
    Failed {
        error: String,
    },
}

/// One recipient a fan-out could not reach, and why.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RefusedRecipient {
    pub to: String,
    pub reason: String,
}

impl Part {
    pub fn text(value: impl Into<String>) -> Self {
        Part::Text { text: value.into() }
    }

    /// The plain-text projection, used for prompts, dedup hashing, and search.
    pub fn as_plain_text(&self) -> Option<&str> {
        match self {
            Part::Text { text } => Some(text),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Envelope {
    pub id: MessageId,
    /// Every envelope belongs to exactly one run. A run is one operator action
    /// plus everything it causes. Budgets are enforced per run, which is the
    /// only unit an operator can reason about.
    pub run_id: RunId,
    /// The agent whose channel this envelope is filed under. See
    /// [`channel_for`] for the rule.
    pub channel_id: AgentId,
    pub from: Participant,
    pub to: Participant,
    pub parts: Vec<Part>,
    pub trust: Trust,
    /// Number of agent-to-agent forwards between the operator and this
    /// envelope. Operator messages start at 0.
    pub hop: u16,
    /// Whether the recipient's answer should be delivered back to the sender.
    ///
    /// True for operator messages and explicit `send_message` calls. False for
    /// automatic replies, and that asymmetry is what makes a cascade terminate:
    /// an agent reading a reply still takes a turn to absorb it, but its output
    /// is filed as a note rather than delivered onward. Without this, two
    /// agents grind against the hop limit being polite at each other.
    pub expects_reply: bool,
    /// The envelope that caused this one, if any. Makes a cascade replayable.
    pub cause: Option<MessageId>,
    pub created_at: i64,
}

impl Envelope {
    /// Concatenated text across parts, used for prompt assembly and hashing.
    pub fn plain_text(&self) -> String {
        self.parts
            .iter()
            .filter_map(Part::as_plain_text)
            .collect::<Vec<_>>()
            .join("\n")
            .trim()
            .to_string()
    }

    /// True when both ends are agents, which is what the activity feed shows.
    pub fn is_inter_agent(&self) -> bool {
        self.from.is_agent() && self.to.is_agent()
    }
}

/// Decides which channel an envelope is filed under.
///
/// One rule, applied at write time rather than inferred at read time: an
/// envelope lives in the channel of the agent at the far end of the human, and
/// when both ends are agents it lives with the recipient. Practically, that
/// means asking one agent to introduce itself fills every other agent's channel
/// with the introduction, and fills the sender's channel with the replies
/// coming back.
pub fn channel_for(from: Participant, to: Participant) -> Option<AgentId> {
    match (from, to) {
        (Participant::Agent { id }, Participant::Human)
        | (Participant::Human, Participant::Agent { id })
        | (Participant::System, Participant::Agent { id })
        | (Participant::Agent { id }, Participant::System) => Some(id),
        (Participant::Agent { .. }, Participant::Agent { id: to_id }) => Some(to_id),
        (Participant::Human, Participant::Human)
        | (Participant::Human, Participant::System)
        | (Participant::System, Participant::Human)
        | (Participant::System, Participant::System) => None,
    }
}

/// Stable fingerprint of "who said what to whom", used by the loop guard to
/// catch an agent pair that has started restating itself.
///
/// Hashes the normalized text only. Whitespace and case differences are not
/// meaningful variation when the question is whether two agents are looping.
pub fn content_fingerprint(from: Participant, to: Participant, text: &str) -> String {
    let normalized = text.split_whitespace().collect::<Vec<_>>().join(" ").to_lowercase();
    let mut hasher = Sha256::new();
    hasher.update(participant_key(from).as_bytes());
    hasher.update(b"->");
    hasher.update(participant_key(to).as_bytes());
    hasher.update(b"|");
    hasher.update(normalized.as_bytes());
    format!("{:x}", hasher.finalize())
}

fn participant_key(p: Participant) -> String {
    match p {
        Participant::Human => "human".to_string(),
        Participant::System => "system".to_string(),
        Participant::Agent { id } => format!("agent:{id}"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn agent(id: AgentId) -> Participant {
        Participant::Agent { id }
    }

    #[test]
    fn human_to_agent_files_under_that_agent() {
        let a = AgentId::new();
        assert_eq!(channel_for(Participant::Human, agent(a)), Some(a));
    }

    #[test]
    fn agent_to_human_files_under_the_same_agent() {
        let a = AgentId::new();
        assert_eq!(
            channel_for(agent(a), Participant::Human),
            Some(a),
            "a reply must land in the channel the operator is reading"
        );
    }

    #[test]
    fn agent_to_agent_files_under_the_recipient() {
        let manager = AgentId::new();
        let chef = AgentId::new();
        assert_eq!(
            channel_for(agent(manager), agent(chef)),
            Some(chef),
            "an introduction should appear in the recipient's channel"
        );
        assert_eq!(
            channel_for(agent(chef), agent(manager)),
            Some(manager),
            "and the reply should come back to the sender's channel"
        );
    }

    #[test]
    fn channelless_pairs_are_rejected_rather_than_defaulted() {
        assert_eq!(channel_for(Participant::Human, Participant::Human), None);
        assert_eq!(channel_for(Participant::System, Participant::Human), None);
    }

    #[test]
    fn fingerprint_ignores_whitespace_and_case() {
        let a = agent(AgentId::new());
        let b = agent(AgentId::new());
        assert_eq!(
            content_fingerprint(a, b, "Hello   there\nfriend"),
            content_fingerprint(a, b, "hello there friend")
        );
    }

    #[test]
    fn fingerprint_is_directional() {
        let a = agent(AgentId::new());
        let b = agent(AgentId::new());
        assert_ne!(
            content_fingerprint(a, b, "hello"),
            content_fingerprint(b, a, "hello"),
            "A->B saying hello is not the same event as B->A saying hello"
        );
    }

    #[test]
    fn fingerprint_separates_participants_from_content() {
        // Without a delimiter between the pair key and the body, an agent could
        // craft text that collides with a different pair's fingerprint.
        let a = AgentId::from_uuid(uuid::Uuid::nil());
        let b = AgentId::new();
        let one = content_fingerprint(agent(a), agent(b), "x");
        let two = content_fingerprint(agent(a), Participant::Human, &format!("agent:{b}|x"));
        assert_ne!(one, two);
    }

    #[test]
    fn plain_text_skips_non_text_parts() {
        let env = Envelope {
            id: MessageId::new(),
            run_id: RunId::new(),
            channel_id: AgentId::new(),
            from: Participant::Human,
            to: agent(AgentId::new()),
            parts: vec![
                Part::text("visible"),
                Part::Notice { kind: NoticeKind::GuardStop, text: "hidden".into() },
                Part::text("also visible"),
            ],
            trust: Trust::Operator,
            hop: 0,
            expects_reply: true,
            cause: None,
            created_at: 0,
        };
        assert_eq!(env.plain_text(), "visible\nalso visible");
    }

    #[test]
    fn inter_agent_detection_excludes_the_human() {
        let a = AgentId::new();
        let b = AgentId::new();
        let base = Envelope {
            id: MessageId::new(),
            run_id: RunId::new(),
            channel_id: b,
            from: agent(a),
            to: agent(b),
            parts: vec![Part::text("hi")],
            trust: Trust::Peer,
            hop: 1,
            expects_reply: true,
            cause: None,
            created_at: 0,
        };
        assert!(base.is_inter_agent());

        let to_human = Envelope { to: Participant::Human, ..base.clone() };
        assert!(!to_human.is_inter_agent());
    }

    #[test]
    fn trust_string_form_round_trips() {
        for t in [Trust::Operator, Trust::Peer, Trust::System] {
            assert_eq!(Trust::parse(t.as_str()), Some(t));
        }
        assert_eq!(Trust::parse("admin"), None);
    }

    #[test]
    fn participant_serializes_with_a_tag_the_frontend_can_switch_on() {
        let json = serde_json::to_value(agent(AgentId::new())).unwrap();
        assert_eq!(json["kind"], "agent");
        assert!(json["id"].is_string());

        let human = serde_json::to_value(Participant::Human).unwrap();
        assert_eq!(human["kind"], "human");
    }
}
